gentoo: Add error message if stage3 image not found
Signed-off-by: Alexey Gladkov <legion@altlinux.org>

diff --git a/vendor/gentoo/chrooted-import-image b/vendor/gentoo/chrooted-import-image
--- a/vendor/gentoo/chrooted-import-image
+++ b/vendor/gentoo/chrooted-import-image
@@ -15,6 +15,11 @@ echo
 path="$(grep -E -e "/stage3-$IMAGE_VAR_ARCH-$IMAGE_VAR_VARIANT-.*.tar.xz " latest-stage3.txt |
 	cut -f1 -d\ )"
 
+if [ -z "$path" ]; then
+	printf >&2 "Error: image not found: %s\n" "stage3-$IMAGE_VAR_ARCH-$IMAGE_VAR_VARIANT-.*.tar.xz"
+	exit 1
+fi
+
 url="https://distfiles.gentoo.org/releases/$IMAGE_VAR_ARCH/autobuilds/$path"
 
 printf >&2 '%s\n' "$PROG: getting $url"
